[build]
  base = "."
  command = "npm install --legacy-peer-deps && ./node_modules/.bin/webpack --config ./webpack/webpack.production.config.babel.js --progress --profile --colors && cp -r public/* build/ && ls -la build/"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"
  BASE_PATH = ""
  GA_ID = ""

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
